// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ProjectlabContext))]
    [Migration("20250425031907_AddIdentityWithIntKeys")]
    partial class AddIdentityWithIntKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<string>("Field")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdAttributeCategory")
                        .HasColumnType("int")
                        .HasColumnName("Id_attribute_category");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("Id_product");

                    b.Property<int?>("IdProductVariant")
                        .HasColumnType("int")
                        .HasColumnName("Id_product_variant");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__attribut__3214EC07319EF739");

                    b.HasIndex("IdAttributeCategory");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdProductVariant");

                    b.ToTable("attribute");
                });

            modelBuilder.Entity("API.Models.AttributeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__attribut__3214EC07371DF6D7");

                    b.ToTable("attribute_category");
                });

            modelBuilder.Entity("API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__cart__3214EC07B8F95698");

                    b.HasIndex("IdUser");

                    b.ToTable("cart");
                });

            modelBuilder.Entity("API.Models.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCart")
                        .HasColumnType("int")
                        .HasColumnName("Id_cart");

                    b.Property<int?>("IdProductVariant")
                        .HasColumnType("int")
                        .HasColumnName("Id_product_variant");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__cart_det__3214EC079CF5115E");

                    b.HasIndex("IdCart");

                    b.HasIndex("IdProductVariant");

                    b.ToTable("cart_detail");
                });

            modelBuilder.Entity("API.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool?>("IsCashback")
                        .HasColumnType("bit")
                        .HasColumnName("Is_cashback");

                    b.Property<bool?>("IsConstant")
                        .HasColumnType("bit")
                        .HasColumnName("Is_constant");

                    b.Property<bool?>("IsPercentual")
                        .HasColumnType("bit")
                        .HasColumnName("Is_percentual");

                    b.Property<bool?>("IsPrimeOnly")
                        .HasColumnType("bit")
                        .HasColumnName("Is_prime_only");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__discount__3214EC0753364700");

                    b.ToTable("discount");
                });

            modelBuilder.Entity("API.Models.FinancePack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<double?>("Interest")
                        .HasColumnType("float");

                    b.Property<int?>("IntervalType")
                        .HasColumnType("int")
                        .HasColumnName("Interval_type");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__finance___3214EC07587F4BB8");

                    b.HasIndex("IntervalType");

                    b.ToTable("finance_pack");
                });

            modelBuilder.Entity("API.Models.FinancePackInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdFinancePack")
                        .HasColumnType("int")
                        .HasColumnName("Id_finance_pack");

                    b.Property<int?>("IntervalCount")
                        .HasColumnType("int")
                        .HasColumnName("Interval_count");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__finance___3214EC07EA6AD922");

                    b.HasIndex("IdFinancePack");

                    b.ToTable("finance_pack_interval");
                });

            modelBuilder.Entity("API.Models.FinancedOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdFinancePack")
                        .HasColumnType("int")
                        .HasColumnName("Id_finance_pack");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("Id_order");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("bit")
                        .HasColumnName("Is_payed");

                    b.Property<double?>("TotalInterest")
                        .HasColumnType("float")
                        .HasColumnName("Total_Interest");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__financed__3214EC0707665F7D");

                    b.HasIndex("IdFinancePack");

                    b.HasIndex("IdOrder");

                    b.ToTable("financed_order");
                });

            modelBuilder.Entity("API.Models.FinancedOrderPay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("Id_order");

                    b.Property<int?>("IdPaymentNumber")
                        .HasColumnType("int")
                        .HasColumnName("Id_payment_number");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("LimitPayDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Limit_pay_date");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Pay_date");

                    b.Property<double?>("PaymentAmount")
                        .HasColumnType("float")
                        .HasColumnName("Payment_amount");

                    b.Property<double?>("TotalPayed")
                        .HasColumnType("float")
                        .HasColumnName("Total_payed");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__financed__3214EC07EEAE7442");

                    b.HasIndex("IdOrder");

                    b.ToTable("financed_order_pay");
                });

            modelBuilder.Entity("API.Models.IntervalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<int?>("TimeInDays")
                        .HasColumnType("int")
                        .HasColumnName("Time_in_days");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__interval__3214EC07877CAC12");

                    b.ToTable("interval_type");
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<int?>("IdUserAddress")
                        .HasColumnType("int")
                        .HasColumnName("Id_user_address");

                    b.Property<int?>("IdUserPaymentCard")
                        .HasColumnType("int")
                        .HasColumnName("Id_user_payment_card");

                    b.Property<int?>("IdUserPaymentPaypal")
                        .HasColumnType("int")
                        .HasColumnName("Id_user_payment_paypal");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool?>("IsFinanced")
                        .HasColumnType("bit")
                        .HasColumnName("Is_financed");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Payment_type");

                    b.Property<int?>("ReferralUser")
                        .HasColumnType("int")
                        .HasColumnName("Referral_user");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("float");

                    b.Property<double?>("Taxes")
                        .HasColumnType("float");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__order__3214EC077CADC2E4");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdUserAddress");

                    b.HasIndex("ReferralUser");

                    b.ToTable("order");
                });

            modelBuilder.Entity("API.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdDiscount")
                        .HasColumnType("int")
                        .HasColumnName("Id_discount");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("Id_order");

                    b.Property<int?>("IdProductVariant")
                        .HasColumnType("int")
                        .HasColumnName("Id_product_variant");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__order_de__3214EC074CA14087");

                    b.HasIndex("IdDiscount");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProductVariant");

                    b.ToTable("order_detail");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<string>("Family")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProductCategory")
                        .HasColumnType("int")
                        .HasColumnName("Product_category");

                    b.Property<string>("ProductType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Product_type");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__product__3214EC073F5578C1");

                    b.HasIndex("ProductCategory");

                    b.ToTable("product");
                });

            modelBuilder.Entity("API.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__product___3214EC0758D9F906");

                    b.ToTable("product_category");
                });

            modelBuilder.Entity("API.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("Id_product");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SKU");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("SubFamily")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Sub_family");

                    b.Property<string>("SubName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Sub_name");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__product___3214EC07DD694D9F");

                    b.HasIndex("IdProduct");

                    b.ToTable("product_variant");
                });

            modelBuilder.Entity("API.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Arrival")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("datetime")
                        .HasColumnName("Estimated_arrival");

                    b.Property<string>("GuideNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Guide_number");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("Id_order");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("ShipmentCompany")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Shipment_company");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Shipment_date");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__shipment__3214EC0791E7D2C0");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdUser");

                    b.ToTable("shipment");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<int?>("LastUsedPayment")
                        .HasColumnType("int")
                        .HasColumnName("Last_used_payment");

                    b.Property<string>("LastUsedPaymentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Last_used_payment_type");

                    b.Property<string>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Referral_code");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address_2");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__user_add__3214EC07685EB650");

                    b.HasIndex("IdUser");

                    b.ToTable("user_address");
                });

            modelBuilder.Entity("API.Models.UserCardPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardExpirationMonth")
                        .HasColumnType("int")
                        .HasColumnName("Card_expiration_month");

                    b.Property<int?>("CardExpirationYear")
                        .HasColumnType("int")
                        .HasColumnName("Card_expiration_year");

                    b.Property<string>("CardName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Card_name");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Card_number");

                    b.Property<string>("CardType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Card_type");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<int?>("IdUserPayment")
                        .HasColumnType("int")
                        .HasColumnName("Id_user_payment");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool?>("LastUsed")
                        .HasColumnType("bit")
                        .HasColumnName("Last_used");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__user_car__3214EC07C7849F62");

                    b.HasIndex("IdUserPayment");

                    b.ToTable("user_card_payment");
                });

            modelBuilder.Entity("API.Models.UserPaypalPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool?>("LastUsed")
                        .HasColumnType("bit")
                        .HasColumnName("Last_used");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("PK__user_pay__3214EC07586740B7");

                    b.HasIndex("UserId");

                    b.ToTable("user_paypal_payment");
                });

            modelBuilder.Entity("API.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Expiration_date");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__user_sub__3214EC075C8D6D9F");

                    b.HasIndex("IdUser");

                    b.ToTable("user_subscription");
                });

            modelBuilder.Entity("API.Models.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Deleted_at");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Expiration_date");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("Id_user");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Update_at");

                    b.HasKey("Id")
                        .HasName("PK__user_wal__3214EC07916EABBE");

                    b.HasIndex("IdUser");

                    b.ToTable("user_wallet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Models.Attribute", b =>
                {
                    b.HasOne("API.Models.AttributeCategory", "IdAttributeCategoryNavigation")
                        .WithMany("Attributes")
                        .HasForeignKey("IdAttributeCategory")
                        .HasConstraintName("FK__attribute__Id_at__6B24EA82");

                    b.HasOne("API.Models.Product", "IdProductNavigation")
                        .WithMany("Attributes")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__attribute__Id_pr__693CA210");

                    b.HasOne("API.Models.ProductVariant", "IdProductVariantNavigation")
                        .WithMany("Attributes")
                        .HasForeignKey("IdProductVariant")
                        .HasConstraintName("FK__attribute__Id_pr__6A30C649");

                    b.Navigation("IdAttributeCategoryNavigation");

                    b.Navigation("IdProductNavigation");

                    b.Navigation("IdProductVariantNavigation");
                });

            modelBuilder.Entity("API.Models.Cart", b =>
                {
                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("Carts")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__cart__Id_user__6477ECF3");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("API.Models.CartDetail", b =>
                {
                    b.HasOne("API.Models.Cart", "IdCartNavigation")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdCart")
                        .HasConstraintName("FK__cart_deta__Id_ca__656C112C");

                    b.HasOne("API.Models.ProductVariant", "IdProductVariantNavigation")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdProductVariant")
                        .HasConstraintName("FK__cart_deta__Id_pr__66603565");

                    b.Navigation("IdCartNavigation");

                    b.Navigation("IdProductVariantNavigation");
                });

            modelBuilder.Entity("API.Models.FinancePack", b =>
                {
                    b.HasOne("API.Models.IntervalType", "IntervalTypeNavigation")
                        .WithMany("FinancePacks")
                        .HasForeignKey("IntervalType")
                        .HasConstraintName("FK__finance_p__Inter__6EF57B66");

                    b.Navigation("IntervalTypeNavigation");
                });

            modelBuilder.Entity("API.Models.FinancePackInterval", b =>
                {
                    b.HasOne("API.Models.FinancePack", "IdFinancePackNavigation")
                        .WithMany("FinancePackIntervals")
                        .HasForeignKey("IdFinancePack")
                        .HasConstraintName("FK__finance_p__Id_fi__6FE99F9F");

                    b.Navigation("IdFinancePackNavigation");
                });

            modelBuilder.Entity("API.Models.FinancedOrder", b =>
                {
                    b.HasOne("API.Models.FinancePack", "IdFinancePackNavigation")
                        .WithMany("FinancedOrders")
                        .HasForeignKey("IdFinancePack")
                        .HasConstraintName("FK__financed___Id_fi__71D1E811");

                    b.HasOne("API.Models.Order", "IdOrderNavigation")
                        .WithMany("FinancedOrders")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK__financed___Id_or__70DDC3D8");

                    b.Navigation("IdFinancePackNavigation");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("API.Models.FinancedOrderPay", b =>
                {
                    b.HasOne("API.Models.FinancedOrder", "IdOrderNavigation")
                        .WithMany("FinancedOrderPays")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK__financed___Id_or__72C60C4A");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("OrderIdUserNavigations")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__order__Id_user__6C190EBB");

                    b.HasOne("API.Models.UserAddress", "IdUserAddressNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdUserAddress")
                        .HasConstraintName("FK__order__Id_user_a__6D0D32F4");

                    b.HasOne("API.Models.User", "ReferralUserNavigation")
                        .WithMany("OrderReferralUserNavigations")
                        .HasForeignKey("ReferralUser")
                        .HasConstraintName("FK__order__Referral___6E01572D");

                    b.Navigation("IdUserAddressNavigation");

                    b.Navigation("IdUserNavigation");

                    b.Navigation("ReferralUserNavigation");
                });

            modelBuilder.Entity("API.Models.OrderDetail", b =>
                {
                    b.HasOne("API.Models.Discount", "IdDiscountNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdDiscount")
                        .HasConstraintName("FK__order_det__Id_di__75A278F5");

                    b.HasOne("API.Models.Order", "IdOrderNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK__order_det__Id_or__73BA3083");

                    b.HasOne("API.Models.ProductVariant", "IdProductVariantNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdProductVariant")
                        .HasConstraintName("FK__order_det__Id_pr__74AE54BC");

                    b.Navigation("IdDiscountNavigation");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdProductVariantNavigation");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.ProductCategory", "ProductCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategory")
                        .HasConstraintName("FK__product__Product__6754599E");

                    b.Navigation("ProductCategoryNavigation");
                });

            modelBuilder.Entity("API.Models.ProductVariant", b =>
                {
                    b.HasOne("API.Models.Product", "IdProductNavigation")
                        .WithMany("ProductVariants")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__product_v__Id_pr__68487DD7");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("API.Models.Shipment", b =>
                {
                    b.HasOne("API.Models.Order", "IdOrderNavigation")
                        .WithMany("Shipments")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK__shipment__Id_ord__76969D2E");

                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("Shipments")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__shipment__Id_use__778AC167");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("API.Models.UserAddress", b =>
                {
                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("UserAddresses")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__user_addr__Id_us__619B8048");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("API.Models.UserCardPayment", b =>
                {
                    b.HasOne("API.Models.User", "IdUserPaymentNavigation")
                        .WithMany("UserCardPayments")
                        .HasForeignKey("IdUserPayment")
                        .HasConstraintName("FK__user_card__Id_us__628FA481");

                    b.Navigation("IdUserPaymentNavigation");
                });

            modelBuilder.Entity("API.Models.UserPaypalPayment", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("UserPaypalPayments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_payp__User___6383C8BA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.UserSubscription", b =>
                {
                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__user_subs__Id_us__60A75C0F");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("API.Models.UserWallet", b =>
                {
                    b.HasOne("API.Models.User", "IdUserNavigation")
                        .WithMany("UserWallets")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__user_wall__Id_us__5FB337D6");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.AttributeCategory", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("API.Models.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("API.Models.Discount", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("API.Models.FinancePack", b =>
                {
                    b.Navigation("FinancePackIntervals");

                    b.Navigation("FinancedOrders");
                });

            modelBuilder.Entity("API.Models.FinancedOrder", b =>
                {
                    b.Navigation("FinancedOrderPays");
                });

            modelBuilder.Entity("API.Models.IntervalType", b =>
                {
                    b.Navigation("FinancePacks");
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.Navigation("FinancedOrders");

                    b.Navigation("OrderDetails");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("API.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("API.Models.ProductVariant", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderIdUserNavigations");

                    b.Navigation("OrderReferralUserNavigations");

                    b.Navigation("Shipments");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserCardPayments");

                    b.Navigation("UserPaypalPayments");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("UserWallets");
                });

            modelBuilder.Entity("API.Models.UserAddress", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
