// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities;

[Table("attribute_category")]
public partial class AttributeCategory
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdAttributeCategoryNavigation")]
    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();
}