// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("attribute")]
public partial class Attribute
{
    [Key]
    public int Id { get; set; }

    [Column("Id_product")]
    public int? IdProduct { get; set; }

    [Column("Id_product_variant")]
    public int? IdProductVariant { get; set; }

    [Column("Id_attribute_category")]
    public int? IdAttributeCategory { get; set; }

    [StringLength(255)]
    public string Field { get; set; }

    [StringLength(255)]
    public string Value { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdAttributeCategory")]
    [InverseProperty("Attributes")]
    public virtual AttributeCategory IdAttributeCategoryNavigation { get; set; }

    [ForeignKey("IdProduct")]
    [InverseProperty("Attributes")]
    public virtual Product IdProductNavigation { get; set; }

    [ForeignKey("IdProductVariant")]
    [InverseProperty("Attributes")]
    public virtual ProductVariant IdProductVariantNavigation { get; set; }
}