// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities;

[Table("cart_detail")]
public partial class CartDetail
{
    [Key]
    public int Id { get; set; }

    [Column("Id_cart")]
    public int? IdCart { get; set; }

    [Column("Id_product_variant")]
    public int? IdProductVariant { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("IdCart")]
    [InverseProperty("CartDetails")]
    public virtual Cart IdCartNavigation { get; set; }

    [ForeignKey("IdProductVariant")]
    [InverseProperty("CartDetails")]
    public virtual ProductVariant IdProductVariantNavigation { get; set; }
}