// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("discount")]
public partial class Discount
{
    [Key]
    public int Id { get; set; }

    [Column("Is_percentual")]
    public bool? IsPercentual { get; set; }

    [Column("Is_constant")]
    public bool? IsConstant { get; set; }

    [Column("Is_cashback")]
    public bool? IsCashback { get; set; }

    [Column("Is_prime_only")]
    public bool? IsPrimeOnly { get; set; }

    public double? Value { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdDiscountNavigation")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}