// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("finance_pack")]
public partial class FinancePack
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [Column("Interval_type")]
    public int? IntervalType { get; set; }

    public double? Interest { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdFinancePackNavigation")]
    public virtual ICollection<FinancePackInterval> FinancePackIntervals { get; set; } = new List<FinancePackInterval>();

    [InverseProperty("IdFinancePackNavigation")]
    public virtual ICollection<FinancedOrder> FinancedOrders { get; set; } = new List<FinancedOrder>();

    [ForeignKey("IntervalType")]
    [InverseProperty("FinancePacks")]
    public virtual IntervalType IntervalTypeNavigation { get; set; }
}