// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("interval_type")]
public partial class IntervalType
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Type { get; set; }

    [Column("Time_in_days")]
    public int? TimeInDays { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IntervalTypeNavigation")]
    public virtual ICollection<FinancePack> FinancePacks { get; set; } = new List<FinancePack>();
}