// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities;

[Keyless]
[Table("order_detail")]
public partial class OrderDetail
{
    [Column("Id_order")]
    public int? IdOrder { get; set; }

    [Column("Id_product")]
    public int? IdProduct { get; set; }

    [Column("Id_discount")]
    public int? IdDiscount { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdDiscount")]
    public virtual Discount IdDiscountNavigation { get; set; }

    [ForeignKey("IdOrder")]
    public virtual Order IdOrderNavigation { get; set; }

    [ForeignKey("IdProduct")]
    public virtual Product IdProductNavigation { get; set; }
}