// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("user_paypal_payment")]
public partial class UserPaypalPayment
{
    [Key]
    public int Id { get; set; }

    [Column("User_id")]
    public int? UserId { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [Column("Last_used")]
    public bool? LastUsed { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserPaypalPayments")]
    public virtual User User { get; set; }
}