// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities.Models.Entities;

[Table("user_card_payment")]
public partial class UserCardPayment
{
    [Key]
    public int Id { get; set; }

    [Column("Id_user_payment")]
    public int? IdUserPayment { get; set; }

    [Column("Card_type")]
    [StringLength(255)]
    public string CardType { get; set; }

    [Column("Card_number")]
    [StringLength(255)]
    public string CardNumber { get; set; }

    [Column("Card_name")]
    [StringLength(255)]
    public string CardName { get; set; }

    [Column("Card_expiration_year")]
    public int? CardExpirationYear { get; set; }

    [Column("Card_expiration_month")]
    public int? CardExpirationMonth { get; set; }

    [Column("Last_used")]
    public bool? LastUsed { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdUserPayment")]
    [InverseProperty("UserCardPayments")]
    public virtual User IdUserPaymentNavigation { get; set; }
}