// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using API.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace API.Data;

public partial class ProjectlabContext : IdentityDbContext<User, IdentityRole<int>, int>
{
    public ProjectlabContext(DbContextOptions<ProjectlabContext> options)
        : base(options)
    {
    }

    public virtual DbSet<API.Models.Attribute> Attributes { get; set; }

    public virtual DbSet<AttributeCategory> AttributeCategories { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartDetail> CartDetails { get; set; }

    public virtual DbSet<Discount> Discounts { get; set; }

    public virtual DbSet<FinancePack> FinancePacks { get; set; }

    public virtual DbSet<FinancePackInterval> FinancePackIntervals { get; set; }

    public virtual DbSet<FinancedOrder> FinancedOrders { get; set; }

    public virtual DbSet<FinancedOrderPay> FinancedOrderPays { get; set; }

    public virtual DbSet<IntervalType> IntervalTypes { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<Shipment> Shipments { get; set; }

    public virtual DbSet<User> UsersU { get; set; }

    public virtual DbSet<UserAddress> UserAddresses { get; set; }

    public virtual DbSet<UserCardPayment> UserCardPayments { get; set; }

    public virtual DbSet<UserPaypalPayment> UserPaypalPayments { get; set; }

    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }

    public virtual DbSet<UserWallet> UserWallets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<API.Models.Attribute>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__attribut__3214EC079B66B196");

            entity.HasOne(d => d.IdAttributeCategoryNavigation).WithMany(p => p.Attributes).HasConstraintName("FK__attribute__Id_at__693CA210");

            entity.HasOne(d => d.IdProductNavigation).WithMany(p => p.Attributes).HasConstraintName("FK__attribute__Id_pr__6754599E");

            entity.HasOne(d => d.IdProductVariantNavigation).WithMany(p => p.Attributes).HasConstraintName("FK__attribute__Id_pr__68487DD7");
        });

        modelBuilder.Entity<AttributeCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__attribut__3214EC079648513B");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__cart__3214EC07DD3EBD57");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Carts).HasConstraintName("FK__cart__Id_user__628FA481");
        });

        modelBuilder.Entity<CartDetail>(entity =>
        {
            entity.HasOne(d => d.IdCartNavigation).WithMany().HasConstraintName("FK__cart_deta__Id_ca__6383C8BA");

            entity.HasOne(d => d.IdProductNavigation).WithMany().HasConstraintName("FK__cart_deta__Id_pr__6477ECF3");
        });

        modelBuilder.Entity<Discount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__discount__3214EC0702ECDCCB");
        });

        modelBuilder.Entity<FinancePack>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__finance___3214EC07229E3F8D");

            entity.HasOne(d => d.IntervalTypeNavigation).WithMany(p => p.FinancePacks).HasConstraintName("FK__finance_p__Inter__6EF57B66");
        });

        modelBuilder.Entity<FinancePackInterval>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__finance___3214EC07C844A178");

            entity.HasOne(d => d.IdFinancePackNavigation).WithMany(p => p.FinancePackIntervals).HasConstraintName("FK__finance_p__Id_fi__6FE99F9F");
        });

        modelBuilder.Entity<FinancedOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__financed__3214EC07181120B4");

            entity.HasOne(d => d.IdFinancePackNavigation).WithMany(p => p.FinancedOrders).HasConstraintName("FK__financed___Id_fi__71D1E811");

            entity.HasOne(d => d.IdOrderNavigation).WithMany(p => p.FinancedOrders).HasConstraintName("FK__financed___Id_or__70DDC3D8");
        });

        modelBuilder.Entity<FinancedOrderPay>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__financed__3214EC07A556F8F3");

            entity.HasOne(d => d.IdOrderNavigation).WithMany(p => p.FinancedOrderPays).HasConstraintName("FK__financed___Id_or__72C60C4A");
        });

        modelBuilder.Entity<IntervalType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__interval__3214EC07A6200E28");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order__3214EC0789601794");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.OrderIdUserNavigations).HasConstraintName("FK__order__Id_user__6A30C649");

            entity.HasOne(d => d.IdUserAddressNavigation).WithMany(p => p.Orders).HasConstraintName("FK__order__Id_user_a__6B24EA82");

            entity.HasOne(d => d.IdUserPaymentCardNavigation).WithMany(p => p.Orders).HasConstraintName("FK__order__Id_user_p__6C190EBB");

            entity.HasOne(d => d.IdUserPaymentPaypalNavigation).WithMany(p => p.Orders).HasConstraintName("FK__order__Id_user_p__6D0D32F4");

            entity.HasOne(d => d.ReferralUserNavigation).WithMany(p => p.OrderReferralUserNavigations).HasConstraintName("FK__order__Referral___6E01572D");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasOne(d => d.IdDiscountNavigation).WithMany().HasConstraintName("FK__order_det__Id_di__75A278F5");

            entity.HasOne(d => d.IdOrderNavigation).WithMany().HasConstraintName("FK__order_det__Id_or__73BA3083");

            entity.HasOne(d => d.IdProductNavigation).WithMany().HasConstraintName("FK__order_det__Id_pr__74AE54BC");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__product__3214EC075A315265");

            entity.HasOne(d => d.ProductCategoryNavigation).WithMany(p => p.Products).HasConstraintName("FK__product__Product__656C112C");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__product___3214EC07E5C9FEB2");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__product___3214EC07B3469FC4");

            entity.HasOne(d => d.IdProductNavigation).WithMany(p => p.ProductVariants).HasConstraintName("FK__product_v__Id_pr__66603565");
        });

        modelBuilder.Entity<Shipment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__shipment__3214EC076B35AE75");

            entity.HasOne(d => d.IdOrderNavigation).WithMany(p => p.Shipments).HasConstraintName("FK__shipment__Id_ord__76969D2E");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Shipments).HasConstraintName("FK__shipment__Id_use__778AC167");
        });

        modelBuilder.Entity<User>(entity =>
        {
            //entity.HasKey(e => e.Id).HasName("PK__user__3214EC07FAAB1726");
        });

        modelBuilder.Entity<UserAddress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_add__3214EC071B191551");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.UserAddresses).HasConstraintName("FK__user_addr__Id_us__5FB337D6");
        });

        modelBuilder.Entity<UserCardPayment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_car__3214EC07D60886DB");

            entity.HasOne(d => d.IdUserPaymentNavigation).WithMany(p => p.UserCardPayments).HasConstraintName("FK__user_card__Id_us__60A75C0F");
        });

        modelBuilder.Entity<UserPaypalPayment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_pay__3214EC071638E603");

            entity.HasOne(d => d.User).WithMany(p => p.UserPaypalPayments).HasConstraintName("FK__user_payp__User___619B8048");
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_sub__3214EC076CD11E24");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.UserSubscriptions).HasConstraintName("FK__user_subs__Id_us__5EBF139D");
        });

        modelBuilder.Entity<UserWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_wal__3214EC07308AF464");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.UserWallets).HasConstraintName("FK__user_wall__Id_us__5DCAEF64");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}