// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Keyless]
[Table("cart_detail")]
public partial class CartDetail
{
    [Column("Id_cart")]
    public int? IdCart { get; set; }

    [Column("Id_product")]
    public int? IdProduct { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("IdCart")]
    public virtual Cart IdCartNavigation { get; set; }

    [ForeignKey("IdProduct")]
    public virtual Product IdProductNavigation { get; set; }
}