// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("finance_pack_interval")]
public partial class FinancePackInterval
{
    [Key]
    public int Id { get; set; }

    [Column("Id_finance_pack")]
    public int? IdFinancePack { get; set; }

    [Column("Interval_count")]
    public int? IntervalCount { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdFinancePack")]
    [InverseProperty("FinancePackIntervals")]
    public virtual FinancePack IdFinancePackNavigation { get; set; }
}