// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("financed_order")]
public partial class FinancedOrder
{
    [Key]
    public int Id { get; set; }

    [Column("Id_order")]
    public int? IdOrder { get; set; }

    [Column("Id_finance_pack")]
    public int? IdFinancePack { get; set; }

    public double? Amount { get; set; }

    [Column("Total_Interest")]
    public double? TotalInterest { get; set; }

    [Column("Is_payed")]
    public bool? IsPayed { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdOrderNavigation")]
    public virtual ICollection<FinancedOrderPay> FinancedOrderPays { get; set; } = new List<FinancedOrderPay>();

    [ForeignKey("IdFinancePack")]
    [InverseProperty("FinancedOrders")]
    public virtual FinancePack IdFinancePackNavigation { get; set; }

    [ForeignKey("IdOrder")]
    [InverseProperty("FinancedOrders")]
    public virtual Order IdOrderNavigation { get; set; }
}