// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("financed_order_pay")]
public partial class FinancedOrderPay
{
    [Key]
    public int Id { get; set; }

    [Column("Id_order")]
    public int? IdOrder { get; set; }

    [Column("Id_payment_number")]
    public int? IdPaymentNumber { get; set; }

    [Column("Payment_amount")]
    public double? PaymentAmount { get; set; }

    [Column("Total_payed")]
    public double? TotalPayed { get; set; }

    [Column("Limit_pay_date", TypeName = "datetime")]
    public DateTime? LimitPayDate { get; set; }

    [Column("Pay_date", TypeName = "datetime")]
    public DateTime? PayDate { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdOrder")]
    [InverseProperty("FinancedOrderPays")]
    public virtual FinancedOrder IdOrderNavigation { get; set; }
}