// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models.Entities;

[Table("order")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    [Column("Id_user")]
    public int? IdUser { get; set; }

    public double? Subtotal { get; set; }

    public double? Taxes { get; set; }

    public double? Total { get; set; }

    [Column("Id_user_address")]
    public int? IdUserAddress { get; set; }

    [Column("Payment_type")]
    [StringLength(255)]
    public string PaymentType { get; set; }

    [Column("Id_user_payment_card")]
    public int? IdUserPaymentCard { get; set; }

    [Column("Id_user_payment_paypal")]
    public int? IdUserPaymentPaypal { get; set; }

    [Column("Is_financed")]
    public bool? IsFinanced { get; set; }

    [Column("Referral_user")]
    public int? ReferralUser { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdOrderNavigation")]
    public virtual ICollection<FinancedOrder> FinancedOrders { get; set; } = new List<FinancedOrder>();

    [ForeignKey("IdUserAddress")]
    [InverseProperty("Orders")]
    public virtual UserAddress IdUserAddressNavigation { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("OrderIdUserNavigations")]
    public virtual User IdUserNavigation { get; set; }

    [ForeignKey("IdUserPaymentCard")]
    [InverseProperty("Orders")]
    public virtual UserCardPayment IdUserPaymentCardNavigation { get; set; }

    [ForeignKey("IdUserPaymentPaypal")]
    [InverseProperty("Orders")]
    public virtual UserPaypalPayment IdUserPaymentPaypalNavigation { get; set; }

    [ForeignKey("ReferralUser")]
    [InverseProperty("OrderReferralUserNavigations")]
    public virtual User ReferralUserNavigation { get; set; }

    [InverseProperty("IdOrderNavigation")]
    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}