// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("product_variant")]
public partial class ProductVariant
{
    [Key]
    public int Id { get; set; }

    [Column("Id_product")]
    public int? IdProduct { get; set; }

    [Column("Sub_name")]
    [StringLength(255)]
    public string SubName { get; set; }

    [Column("SKU")]
    [StringLength(255)]
    public string Sku { get; set; }

    [Column("Sub_family")]
    [StringLength(255)]
    public string SubFamily { get; set; }

    public double? Price { get; set; }

    public int? Stock { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdProductVariantNavigation")]
    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();

    [InverseProperty("IdProductVariantNavigation")]
    public virtual ICollection<CartDetail> CartDetails { get; set; } = new List<CartDetail>();

    [ForeignKey("IdProduct")]
    [InverseProperty("ProductVariants")]
    public virtual Product IdProductNavigation { get; set; }

    [InverseProperty("IdProductVariantNavigation")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}