// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("product")]
public partial class Product : IDisposable
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [Column("Product_type")]
    [StringLength(255)]
    public string ProductType { get; set; }

    [Column("Product_category")]
    public int? ProductCategory { get; set; }

    [StringLength(255)]
    public string Brand { get; set; }

    [StringLength(255)]
    public string Family { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();

    [ForeignKey("ProductCategory")]
    [InverseProperty("Products")]
    public virtual ProductCategory ProductCategoryNavigation { get; set; }

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    bool disposed;

    protected virtual void Dispose(bool disposing)
    {
        if (!disposed)
        {
            if (disposing)
            {
                //dispose managed resources
            }
        }
        //dispose unmanaged resources
        disposed = true;
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }
}