// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("shipment")]
public partial class Shipment
{
    [Key]
    public int Id { get; set; }

    [Column("Id_order")]
    public int? IdOrder { get; set; }

    [Column("Id_user")]
    public int? IdUser { get; set; }

    [Column("Shipment_company")]
    [StringLength(255)]
    public string ShipmentCompany { get; set; }

    [Column("Guide_number")]
    [StringLength(255)]
    public string GuideNumber { get; set; }

    [Column("Shipment_date", TypeName = "datetime")]
    public DateTime? ShipmentDate { get; set; }

    [Column("Estimated_arrival", TypeName = "datetime")]
    public DateTime? EstimatedArrival { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Arrival { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdOrder")]
    [InverseProperty("Shipments")]
    public virtual Order IdOrderNavigation { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("Shipments")]
    public virtual User IdUserNavigation { get; set; }
}