// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("user_wallet")]
public partial class UserWallet
{
    [Key]
    public int Id { get; set; }

    [Column("Id_user")]
    public int? IdUser { get; set; }

    [StringLength(255)]
    public string Currency { get; set; }

    public double? Amount { get; set; }

    [Column("Expiration_date", TypeName = "datetime")]
    public DateTime? ExpirationDate { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("UserWallets")]
    public virtual User IdUserNavigation { get; set; }
}