// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("user_address")]
public partial class UserAddress
{
    [Key]
    public int Id { get; set; }

    [Column("Id_user")]
    public int? IdUser { get; set; }

    [Column("Address_1")]
    [StringLength(255)]
    public string Address1 { get; set; }

    [Column("Address_2")]
    [StringLength(255)]
    public string Address2 { get; set; }

    [Column("Postal_code")]
    [StringLength(255)]
    public string PostalCode { get; set; }

    [StringLength(255)]
    public string Country { get; set; }

    [StringLength(255)]
    public string State { get; set; }

    [StringLength(255)]
    public string City { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("UserAddresses")]
    public virtual User IdUserNavigation { get; set; }

    [InverseProperty("IdUserAddressNavigation")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}