// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace API.Models;

[Table("user")]
public class User : IdentityUser<int>
{
    
    [StringLength(255)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Lastname { get; set; }

    [Column("Referral_code")]
    [StringLength(255)]
    public string ReferralCode { get; set; }

    [Column("Last_used_payment_type")]
    [StringLength(255)]
    public string LastUsedPaymentType { get; set; }

    [Column("Last_used_payment")]
    public int? LastUsedPayment { get; set; }

    [Column("Created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("Update_at", TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [Column("Deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("Is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<Order> OrderIdUserNavigations { get; set; } = new List<Order>();

    [InverseProperty("ReferralUserNavigation")]
    public virtual ICollection<Order> OrderReferralUserNavigations { get; set; } = new List<Order>();

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();

    [InverseProperty("IdUserPaymentNavigation")]
    public virtual ICollection<UserCardPayment> UserCardPayments { get; set; } = new List<UserCardPayment>();

    [InverseProperty("User")]
    public virtual ICollection<UserPaypalPayment> UserPaypalPayments { get; set; } = new List<UserPaypalPayment>();

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();

    [InverseProperty("IdUserNavigation")]
    public virtual ICollection<UserWallet> UserWallets { get; set; } = new List<UserWallet>();
}